/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import java.awt.Color;

/**
 *
 * @author Juan WT
 */
public class JFMenu extends javax.swing.JFrame {

    /**
     * Creates new form JFMenu
     */
    public JFMenu() {
        initComponents();
        JPEscritorio.setBackground(new Color(213, 134, 145, 123));
        //this.setExtendedState(MAXIMIZED_BOTH);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPEscritorio = new org.edisoncor.gui.panel.Panel();
        jMenuBar1 = new javax.swing.JMenuBar();
        btnMantenimiento = new javax.swing.JMenu();
        btnClientes = new javax.swing.JMenuItem();
        btnProveedores = new javax.swing.JMenuItem();
        btnProductos = new javax.swing.JMenuItem();
        btnTipoDocumento = new javax.swing.JMenuItem();
        btnVariablesParametrizables = new javax.swing.JMenuItem();
        btnCompras = new javax.swing.JMenu();
        btnPedidos = new javax.swing.JMenuItem();
        btnCompras1 = new javax.swing.JMenuItem();
        btnDevoluciones = new javax.swing.JMenuItem();
        btnFacturacionMenu = new javax.swing.JMenu();
        btnVentas = new javax.swing.JMenuItem();
        btnCotizaciones = new javax.swing.JMenuItem();
        btnDevolucines = new javax.swing.JMenuItem();
        btnInvetarioBodega = new javax.swing.JMenu();
        btnComprasInven = new javax.swing.JMenuItem();
        btnInventario = new javax.swing.JMenuItem();
        btnReportes = new javax.swing.JMenuItem();
        btnContabilidad = new javax.swing.JMenu();
        btnNotasdeDevito = new javax.swing.JMenuItem();
        btnRetenciones = new javax.swing.JMenuItem();
        btnNotasdeCredito = new javax.swing.JMenuItem();
        btnReportesMenu = new javax.swing.JMenu();
        btnReportesClientes = new javax.swing.JMenuItem();
        btnReportesProductos = new javax.swing.JMenuItem();
        btnReportesProveedores = new javax.swing.JMenuItem();
        btnVentasdiarias = new javax.swing.JMenuItem();
        btnVentasMensuales = new javax.swing.JMenuItem();
        btnReportesContables = new javax.swing.JMenuItem();
        btnSeguridad = new javax.swing.JMenu();
        btnUsuariosSistema = new javax.swing.JMenuItem();
        btnResetearClave = new javax.swing.JMenuItem();
        btnResetarClaveAdmin = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JPEscritorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/boutiqueWolf.png"))); // NOI18N

        javax.swing.GroupLayout JPEscritorioLayout = new javax.swing.GroupLayout(JPEscritorio);
        JPEscritorio.setLayout(JPEscritorioLayout);
        JPEscritorioLayout.setHorizontalGroup(
            JPEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 824, Short.MAX_VALUE)
        );
        JPEscritorioLayout.setVerticalGroup(
            JPEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 497, Short.MAX_VALUE)
        );

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 204));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jMenuBar1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        btnMantenimiento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/ajustes.png"))); // NOI18N
        btnMantenimiento.setText("Mantenimiento");
        btnMantenimiento.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnMantenimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMantenimientoActionPerformed(evt);
            }
        });

        btnClientes.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Clientes.png"))); // NOI18N
        btnClientes.setText("Clientes");
        btnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesActionPerformed(evt);
            }
        });
        btnMantenimiento.add(btnClientes);

        btnProveedores.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnProveedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/proveedores.png"))); // NOI18N
        btnProveedores.setText("Proveedores");
        btnProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProveedoresActionPerformed(evt);
            }
        });
        btnMantenimiento.add(btnProveedores);

        btnProductos.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/PRODUCTOS-1.png"))); // NOI18N
        btnProductos.setText("Productos");
        btnProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductosActionPerformed(evt);
            }
        });
        btnMantenimiento.add(btnProductos);

        btnTipoDocumento.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnTipoDocumento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/tipoDocumento.png"))); // NOI18N
        btnTipoDocumento.setText("Tipo Documento");
        btnTipoDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTipoDocumentoActionPerformed(evt);
            }
        });
        btnMantenimiento.add(btnTipoDocumento);

        btnVariablesParametrizables.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnVariablesParametrizables.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/variables.png"))); // NOI18N
        btnVariablesParametrizables.setText("Variables Parametrizables");
        btnVariablesParametrizables.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVariablesParametrizablesActionPerformed(evt);
            }
        });
        btnMantenimiento.add(btnVariablesParametrizables);

        jMenuBar1.add(btnMantenimiento);

        btnCompras.setBackground(new java.awt.Color(204, 255, 204));
        btnCompras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/comprasPrin.png"))); // NOI18N
        btnCompras.setText("Compras");
        btnCompras.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprasActionPerformed(evt);
            }
        });

        btnPedidos.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnPedidos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/pedidos.png"))); // NOI18N
        btnPedidos.setText("Pedidos");
        btnPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPedidosActionPerformed(evt);
            }
        });
        btnCompras.add(btnPedidos);

        btnCompras1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnCompras1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/compraspro.png"))); // NOI18N
        btnCompras1.setText("Compras");
        btnCompras1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompras1ActionPerformed(evt);
            }
        });
        btnCompras.add(btnCompras1);

        btnDevoluciones.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnDevoluciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/devoluciones.png"))); // NOI18N
        btnDevoluciones.setText("Devoluciones");
        btnDevoluciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDevolucionesActionPerformed(evt);
            }
        });
        btnCompras.add(btnDevoluciones);

        jMenuBar1.add(btnCompras);

        btnFacturacionMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/iconofacturacion.jpe"))); // NOI18N
        btnFacturacionMenu.setText("Facturación");
        btnFacturacionMenu.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnFacturacionMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFacturacionMenuActionPerformed(evt);
            }
        });

        btnVentas.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/iconoVentas.png"))); // NOI18N
        btnVentas.setText("Ventas");
        btnVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentasActionPerformed(evt);
            }
        });
        btnFacturacionMenu.add(btnVentas);

        btnCotizaciones.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnCotizaciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/cotizacion.png"))); // NOI18N
        btnCotizaciones.setText("Cotizaciones");
        btnCotizaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCotizacionesActionPerformed(evt);
            }
        });
        btnFacturacionMenu.add(btnCotizaciones);

        btnDevolucines.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnDevolucines.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/devoluciones.png"))); // NOI18N
        btnDevolucines.setText("Devoluciones");
        btnDevolucines.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDevolucinesActionPerformed(evt);
            }
        });
        btnFacturacionMenu.add(btnDevolucines);

        jMenuBar1.add(btnFacturacionMenu);

        btnInvetarioBodega.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/iconoInventario.jpg"))); // NOI18N
        btnInvetarioBodega.setText("Inventario/Bodega");
        btnInvetarioBodega.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnInvetarioBodega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInvetarioBodegaActionPerformed(evt);
            }
        });

        btnComprasInven.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnComprasInven.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/iconCompras.png"))); // NOI18N
        btnComprasInven.setText("Compras");
        btnComprasInven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprasInvenActionPerformed(evt);
            }
        });
        btnInvetarioBodega.add(btnComprasInven);

        btnInventario.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnInventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/iconoInventario.jpg"))); // NOI18N
        btnInventario.setText("Inventarios");
        btnInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInventarioActionPerformed(evt);
            }
        });
        btnInvetarioBodega.add(btnInventario);

        btnReportes.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/iconoReportes.jpg"))); // NOI18N
        btnReportes.setText("Reportes");
        btnReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportesActionPerformed(evt);
            }
        });
        btnInvetarioBodega.add(btnReportes);

        jMenuBar1.add(btnInvetarioBodega);

        btnContabilidad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Contabilidad.png"))); // NOI18N
        btnContabilidad.setText("Contabilidad");
        btnContabilidad.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnContabilidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContabilidadActionPerformed(evt);
            }
        });

        btnNotasdeDevito.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnNotasdeDevito.setText("Notas de Debito");
        btnNotasdeDevito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNotasdeDevitoActionPerformed(evt);
            }
        });
        btnContabilidad.add(btnNotasdeDevito);

        btnRetenciones.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnRetenciones.setText("Retenciones");
        btnRetenciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetencionesActionPerformed(evt);
            }
        });
        btnContabilidad.add(btnRetenciones);

        btnNotasdeCredito.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnNotasdeCredito.setText("Notas de Credito");
        btnNotasdeCredito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNotasdeCreditoActionPerformed(evt);
            }
        });
        btnContabilidad.add(btnNotasdeCredito);

        jMenuBar1.add(btnContabilidad);

        btnReportesMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Reporte_I.png"))); // NOI18N
        btnReportesMenu.setText("Reportes");
        btnReportesMenu.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnReportesMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportesMenuActionPerformed(evt);
            }
        });

        btnReportesClientes.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnReportesClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/iconocliente.jpe"))); // NOI18N
        btnReportesClientes.setText("Clientes");
        btnReportesClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportesClientesActionPerformed(evt);
            }
        });
        btnReportesMenu.add(btnReportesClientes);

        btnReportesProductos.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnReportesProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/PRODUCTOS-1.png"))); // NOI18N
        btnReportesProductos.setText("Productos");
        btnReportesProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportesProductosActionPerformed(evt);
            }
        });
        btnReportesMenu.add(btnReportesProductos);

        btnReportesProveedores.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnReportesProveedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/proveedores.png"))); // NOI18N
        btnReportesProveedores.setText("Provedores");
        btnReportesProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportesProveedoresActionPerformed(evt);
            }
        });
        btnReportesMenu.add(btnReportesProveedores);

        btnVentasdiarias.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnVentasdiarias.setText("Ventas Diarias/Arqueo de Caja");
        btnVentasdiarias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentasdiariasActionPerformed(evt);
            }
        });
        btnReportesMenu.add(btnVentasdiarias);

        btnVentasMensuales.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnVentasMensuales.setText("Ventas Mensuales");
        btnVentasMensuales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentasMensualesActionPerformed(evt);
            }
        });
        btnReportesMenu.add(btnVentasMensuales);

        btnReportesContables.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnReportesContables.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/ico_24.png"))); // NOI18N
        btnReportesContables.setText("Reportes Contables");
        btnReportesContables.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportesContablesActionPerformed(evt);
            }
        });
        btnReportesMenu.add(btnReportesContables);

        jMenuBar1.add(btnReportesMenu);

        btnSeguridad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/icono-seguridad-y-cerradura-planos-del-candado-95215260.jpg"))); // NOI18N
        btnSeguridad.setText("Seguridad");
        btnSeguridad.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnSeguridad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeguridadActionPerformed(evt);
            }
        });

        btnUsuariosSistema.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnUsuariosSistema.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/user.png"))); // NOI18N
        btnUsuariosSistema.setText("Administrar Usuarios del Sistema");
        btnUsuariosSistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuariosSistemaActionPerformed(evt);
            }
        });
        btnSeguridad.add(btnUsuariosSistema);

        btnResetearClave.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnResetearClave.setText("Resetear Clave");
        btnResetearClave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetearClaveActionPerformed(evt);
            }
        });
        btnSeguridad.add(btnResetearClave);

        btnResetarClaveAdmin.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnResetarClaveAdmin.setText("Resetear clave Admin");
        btnResetarClaveAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetarClaveAdminActionPerformed(evt);
            }
        });
        btnSeguridad.add(btnResetarClaveAdmin);

        jMenuBar1.add(btnSeguridad);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JPEscritorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(JPEscritorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPedidosActionPerformed
        JIFPedidos pedidos=new JIFPedidos();
        getJPEscritorio().removeAll();
        getJPEscritorio().add(pedidos);
        pedidos.setSize(736, 441);
        pedidos.setVisible(true);
    }//GEN-LAST:event_btnPedidosActionPerformed

    private void btnCompras1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompras1ActionPerformed
        JIFCompras compras=new JIFCompras();
        getJPEscritorio().removeAll();
        getJPEscritorio().add(compras);
        compras.setSize(736, 441);
        compras.setVisible(true);
    }//GEN-LAST:event_btnCompras1ActionPerformed

    private void btnCotizacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCotizacionesActionPerformed
        JIFCotizaciones cotizaciones=new JIFCotizaciones();
        getJPEscritorio().removeAll();
        getJPEscritorio().add(cotizaciones);
        cotizaciones.setSize(736, 441);
        cotizaciones.setVisible(true);
    }//GEN-LAST:event_btnCotizacionesActionPerformed

    private void btnNotasdeDevitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNotasdeDevitoActionPerformed
        JIFNotasDevito notasDevito =new JIFNotasDevito();
        getJPEscritorio().removeAll();
        getJPEscritorio().add(notasDevito);
        notasDevito.setSize(736, 441);
        notasDevito.setVisible(true);
    }//GEN-LAST:event_btnNotasdeDevitoActionPerformed

    private void btnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesActionPerformed
        JIFClientes clientes=new JIFClientes();
        getJPEscritorio().removeAll();
        getJPEscritorio().add(clientes);
        clientes.setSize(736, 441);
        clientes.setVisible(true);
    }//GEN-LAST:event_btnClientesActionPerformed

    private void btnProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProveedoresActionPerformed
        JIFProvedores provedores=new JIFProvedores();
        getJPEscritorio().removeAll();
        getJPEscritorio().add(provedores);
        provedores.setSize(736, 441);
        provedores.setVisible(true);
    }//GEN-LAST:event_btnProveedoresActionPerformed

    private void btnProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductosActionPerformed
        JIFProductos productos=new JIFProductos();
        getJPEscritorio().removeAll();
        getJPEscritorio().add(productos);
        productos.setSize(736, 441);
        productos.setVisible(true);
    }//GEN-LAST:event_btnProductosActionPerformed

    private void btnTipoDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTipoDocumentoActionPerformed
        JIFTipoDocumento documento=new JIFTipoDocumento();
        getJPEscritorio().removeAll();
        getJPEscritorio().add(documento);
        getJPEscritorio().revalidate();
        documento.setSize(736, 441);
        documento.setVisible(true);
    }//GEN-LAST:event_btnTipoDocumentoActionPerformed

    private void btnVariablesParametrizablesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVariablesParametrizablesActionPerformed
        JIFVariablesP variablesP=new JIFVariablesP();
        getJPEscritorio().removeAll();
        getJPEscritorio().add(variablesP);
        getJPEscritorio().revalidate();
        variablesP.setSize(736, 441);
        variablesP.setVisible(true);
        getJPEscritorio().setOpaque(false);
        variablesP.setOpaque(false);
    }//GEN-LAST:event_btnVariablesParametrizablesActionPerformed

    private void btnUsuariosSistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuariosSistemaActionPerformed
        JIFUsuarios usuarios=new JIFUsuarios();
        getJPEscritorio().removeAll();
        getJPEscritorio().add(usuarios);
        getJPEscritorio().revalidate();
        usuarios.setSize(736, 441);
        usuarios.setVisible(true);
    }//GEN-LAST:event_btnUsuariosSistemaActionPerformed

    private void btnVentasdiariasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentasdiariasActionPerformed
        JIFVentasDiarias ventasDiarias=new JIFVentasDiarias();
        JIFReportesClientes clientes=new JIFReportesClientes();
        getJPEscritorio().removeAll();
        getJPEscritorio().add(ventasDiarias);
        ventasDiarias.setSize(736, 441);
        ventasDiarias.setVisible(true);
    }//GEN-LAST:event_btnVentasdiariasActionPerformed

    private void btnDevolucionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDevolucionesActionPerformed
        JIFDevoluciones devoluciones=new JIFDevoluciones();
        getJPEscritorio().removeAll();
        getJPEscritorio().add(devoluciones);
        devoluciones.setSize(736, 441);
        devoluciones.setVisible(true);
    }//GEN-LAST:event_btnDevolucionesActionPerformed

    private void btnVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentasActionPerformed
        JIFVentas ventas=new JIFVentas();
        getJPEscritorio().removeAll();
        getJPEscritorio().add(ventas);
        ventas.setSize(736, 441);
        ventas.setVisible(true);
    }//GEN-LAST:event_btnVentasActionPerformed

    private void btnDevolucinesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDevolucinesActionPerformed
        JIFDevolucionesVen devoluciones=new JIFDevolucionesVen();
        getJPEscritorio().removeAll();
        getJPEscritorio().add(devoluciones);
        devoluciones.setSize(736, 441);
        devoluciones.setVisible(true);
    }//GEN-LAST:event_btnDevolucinesActionPerformed

    private void btnComprasInvenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprasInvenActionPerformed
        JIFComprasInv comprasInv=new JIFComprasInv();
        getJPEscritorio().removeAll();
        getJPEscritorio().add(comprasInv);
        comprasInv.setSize(736, 441);
        comprasInv.setVisible(true);
    }//GEN-LAST:event_btnComprasInvenActionPerformed

    private void btnInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInventarioActionPerformed
        JIFInvetarios fInvetarios=new JIFInvetarios();
        getJPEscritorio().removeAll();
        getJPEscritorio().add(fInvetarios);
        fInvetarios.setSize(736, 441);
        fInvetarios.setVisible(true);
    }//GEN-LAST:event_btnInventarioActionPerformed

    private void btnReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesActionPerformed
        JIFReportes reportes=new JIFReportes();
        getJPEscritorio().removeAll();
        getJPEscritorio().add(reportes);
        reportes.setSize(736, 441);
        reportes.setVisible(true);
    }//GEN-LAST:event_btnReportesActionPerformed

    private void btnRetencionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetencionesActionPerformed
        JIFRetenciones retenciones=new JIFRetenciones();
        getJPEscritorio().removeAll();
        getJPEscritorio().add(retenciones);
        retenciones.setSize(736, 441);
        retenciones.setVisible(true);
    }//GEN-LAST:event_btnRetencionesActionPerformed

    private void btnNotasdeCreditoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNotasdeCreditoActionPerformed
        JIFNotasCredito credito=new JIFNotasCredito();
        getJPEscritorio().removeAll();
        getJPEscritorio().add(credito);
        credito.setSize(736, 441);
        credito.setVisible(true);
    }//GEN-LAST:event_btnNotasdeCreditoActionPerformed

    private void btnReportesClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesClientesActionPerformed
        JIFReportesClientes clientes=new JIFReportesClientes();
        getJPEscritorio().removeAll();
        getJPEscritorio().add(clientes);
        clientes.setSize(736, 441);
        clientes.setVisible(true);
    }//GEN-LAST:event_btnReportesClientesActionPerformed

    private void btnReportesProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesProductosActionPerformed
        JIFReportesProductos reportesProductos=new JIFReportesProductos();
        getJPEscritorio().removeAll();
        getJPEscritorio().add(reportesProductos);
        reportesProductos.setSize(736, 441);
        reportesProductos.setVisible(true);
    }//GEN-LAST:event_btnReportesProductosActionPerformed

    private void btnReportesProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesProveedoresActionPerformed
        JIFReportesClientes clientes=new JIFReportesClientes();
        getJPEscritorio().removeAll();
        getJPEscritorio().add(clientes);
        clientes.setSize(736, 441);
        clientes.setVisible(true);
    }//GEN-LAST:event_btnReportesProveedoresActionPerformed

    private void btnVentasMensualesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentasMensualesActionPerformed
        JIFReportesClientes clientes=new JIFReportesClientes();
        getJPEscritorio().removeAll();
        getJPEscritorio().add(clientes);
        clientes.setSize(736, 441);
        clientes.setVisible(true);
    }//GEN-LAST:event_btnVentasMensualesActionPerformed

    private void btnReportesContablesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesContablesActionPerformed
        JIFReportesContables reportesContables=new JIFReportesContables();
        getJPEscritorio().removeAll();
        getJPEscritorio().add(reportesContables);
        reportesContables.setSize(736, 441);
        reportesContables.setVisible(true);
    }//GEN-LAST:event_btnReportesContablesActionPerformed

    private void btnResetearClaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetearClaveActionPerformed
        JIFCambiarClaveUsuario clave=new JIFCambiarClaveUsuario();
        getJPEscritorio().removeAll();
        getJPEscritorio().add(clave);
        clave.setSize(736, 441);
        clave.setVisible(true);
    }//GEN-LAST:event_btnResetearClaveActionPerformed

    private void btnMantenimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMantenimientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMantenimientoActionPerformed

    private void btnComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnComprasActionPerformed

    private void btnFacturacionMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFacturacionMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFacturacionMenuActionPerformed

    private void btnInvetarioBodegaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInvetarioBodegaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInvetarioBodegaActionPerformed

    private void btnContabilidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContabilidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnContabilidadActionPerformed

    private void btnReportesMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReportesMenuActionPerformed

    private void btnSeguridadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeguridadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSeguridadActionPerformed

    private void btnResetarClaveAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetarClaveAdminActionPerformed
        JIFCambiarClaveAdmin cambiarClaveAdmin=new JIFCambiarClaveAdmin();
        getJPEscritorio().removeAll();
        getJPEscritorio().add(cambiarClaveAdmin);
        getJPEscritorio().revalidate();
        cambiarClaveAdmin.setSize(736, 441);
        cambiarClaveAdmin.setVisible(true);
        getJPEscritorio().setOpaque(false);
        cambiarClaveAdmin.setOpaque(false);
    }//GEN-LAST:event_btnResetarClaveAdminActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.edisoncor.gui.panel.Panel JPEscritorio;
    private javax.swing.JMenuItem btnClientes;
    private javax.swing.JMenu btnCompras;
    private javax.swing.JMenuItem btnCompras1;
    private javax.swing.JMenuItem btnComprasInven;
    private javax.swing.JMenu btnContabilidad;
    private javax.swing.JMenuItem btnCotizaciones;
    private javax.swing.JMenuItem btnDevolucines;
    private javax.swing.JMenuItem btnDevoluciones;
    private javax.swing.JMenu btnFacturacionMenu;
    private javax.swing.JMenuItem btnInventario;
    private javax.swing.JMenu btnInvetarioBodega;
    private javax.swing.JMenu btnMantenimiento;
    private javax.swing.JMenuItem btnNotasdeCredito;
    private javax.swing.JMenuItem btnNotasdeDevito;
    private javax.swing.JMenuItem btnPedidos;
    private javax.swing.JMenuItem btnProductos;
    private javax.swing.JMenuItem btnProveedores;
    private javax.swing.JMenuItem btnReportes;
    private javax.swing.JMenuItem btnReportesClientes;
    private javax.swing.JMenuItem btnReportesContables;
    private javax.swing.JMenu btnReportesMenu;
    private javax.swing.JMenuItem btnReportesProductos;
    private javax.swing.JMenuItem btnReportesProveedores;
    private javax.swing.JMenuItem btnResetarClaveAdmin;
    private javax.swing.JMenuItem btnResetearClave;
    private javax.swing.JMenuItem btnRetenciones;
    private javax.swing.JMenu btnSeguridad;
    private javax.swing.JMenuItem btnTipoDocumento;
    private javax.swing.JMenuItem btnUsuariosSistema;
    private javax.swing.JMenuItem btnVariablesParametrizables;
    private javax.swing.JMenuItem btnVentas;
    private javax.swing.JMenuItem btnVentasMensuales;
    private javax.swing.JMenuItem btnVentasdiarias;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the btnMantenimiento
     */
    public javax.swing.JMenu getBtnMantenimiento() {
        return btnMantenimiento;
    }

    /**
     * @param btnMantenimiento the btnMantenimiento to set
     */
    public void setBtnMantenimiento(javax.swing.JMenu btnMantenimiento) {
        this.btnMantenimiento = btnMantenimiento;
    }

    /**
     * @return the JPEscritorio
     */
    public org.edisoncor.gui.panel.Panel getJPEscritorio() {
        return JPEscritorio;
    }

    /**
     * @param JPEscritorio the JPEscritorio to set
     */
    public void setJPEscritorio(org.edisoncor.gui.panel.Panel JPEscritorio) {
        this.JPEscritorio = JPEscritorio;
    }

    /**
     * @return the btnClientes
     */
    public javax.swing.JMenuItem getBtnClientes() {
        return btnClientes;
    }

    /**
     * @param btnClientes the btnClientes to set
     */
    public void setBtnClientes(javax.swing.JMenuItem btnClientes) {
        this.btnClientes = btnClientes;
    }

    /**
     * @return the btnCompras
     */
    public javax.swing.JMenu getBtnCompras() {
        return btnCompras;
    }

    /**
     * @param btnCompras the btnCompras to set
     */
    public void setBtnCompras(javax.swing.JMenu btnCompras) {
        this.btnCompras = btnCompras;
    }

    /**
     * @return the btnCompras1
     */
    public javax.swing.JMenuItem getBtnCompras1() {
        return btnCompras1;
    }

    /**
     * @param btnCompras1 the btnCompras1 to set
     */
    public void setBtnCompras1(javax.swing.JMenuItem btnCompras1) {
        this.btnCompras1 = btnCompras1;
    }

    /**
     * @return the btnComprasInven
     */
    public javax.swing.JMenuItem getBtnComprasInven() {
        return btnComprasInven;
    }

    /**
     * @param btnComprasInven the btnComprasInven to set
     */
    public void setBtnComprasInven(javax.swing.JMenuItem btnComprasInven) {
        this.btnComprasInven = btnComprasInven;
    }

    /**
     * @return the btnContabilidad
     */
    public javax.swing.JMenu getBtnContabilidad() {
        return btnContabilidad;
    }

    /**
     * @param btnContabilidad the btnContabilidad to set
     */
    public void setBtnContabilidad(javax.swing.JMenu btnContabilidad) {
        this.btnContabilidad = btnContabilidad;
    }

    /**
     * @return the btnCotizaciones
     */
    public javax.swing.JMenuItem getBtnCotizaciones() {
        return btnCotizaciones;
    }

    /**
     * @param btnCotizaciones the btnCotizaciones to set
     */
    public void setBtnCotizaciones(javax.swing.JMenuItem btnCotizaciones) {
        this.btnCotizaciones = btnCotizaciones;
    }

    /**
     * @return the btnDevolucines
     */
    public javax.swing.JMenuItem getBtnDevolucines() {
        return btnDevolucines;
    }

    /**
     * @param btnDevolucines the btnDevolucines to set
     */
    public void setBtnDevolucines(javax.swing.JMenuItem btnDevolucines) {
        this.btnDevolucines = btnDevolucines;
    }

    /**
     * @return the btnDevoluciones
     */
    public javax.swing.JMenuItem getBtnDevoluciones() {
        return btnDevoluciones;
    }

    /**
     * @param btnDevoluciones the btnDevoluciones to set
     */
    public void setBtnDevoluciones(javax.swing.JMenuItem btnDevoluciones) {
        this.btnDevoluciones = btnDevoluciones;
    }

    /**
     * @return the btnFacturacionMenu
     */
    public javax.swing.JMenu getBtnFacturacionMenu() {
        return btnFacturacionMenu;
    }

    /**
     * @param btnFacturacionMenu the btnFacturacionMenu to set
     */
    public void setBtnFacturacionMenu(javax.swing.JMenu btnFacturacionMenu) {
        this.btnFacturacionMenu = btnFacturacionMenu;
    }

    /**
     * @return the btnInventario
     */
    public javax.swing.JMenuItem getBtnInventario() {
        return btnInventario;
    }

    /**
     * @param btnInventario the btnInventario to set
     */
    public void setBtnInventario(javax.swing.JMenuItem btnInventario) {
        this.btnInventario = btnInventario;
    }

    /**
     * @return the btnInvetarioBodega
     */
    public javax.swing.JMenu getBtnInvetarioBodega() {
        return btnInvetarioBodega;
    }

    /**
     * @param btnInvetarioBodega the btnInvetarioBodega to set
     */
    public void setBtnInvetarioBodega(javax.swing.JMenu btnInvetarioBodega) {
        this.btnInvetarioBodega = btnInvetarioBodega;
    }


    /**
     * @return the btnNotasdeCredito
     */
    public javax.swing.JMenuItem getBtnNotasdeCredito() {
        return btnNotasdeCredito;
    }

    /**
     * @param btnNotasdeCredito the btnNotasdeCredito to set
     */
    public void setBtnNotasdeCredito(javax.swing.JMenuItem btnNotasdeCredito) {
        this.btnNotasdeCredito = btnNotasdeCredito;
    }

    /**
     * @return the btnNotasdeDevito
     */
    public javax.swing.JMenuItem getBtnNotasdeDevito() {
        return btnNotasdeDevito;
    }

    /**
     * @param btnNotasdeDevito the btnNotasdeDevito to set
     */
    public void setBtnNotasdeDevito(javax.swing.JMenuItem btnNotasdeDevito) {
        this.btnNotasdeDevito = btnNotasdeDevito;
    }

    /**
     * @return the btnPedidos
     */
    public javax.swing.JMenuItem getBtnPedidos() {
        return btnPedidos;
    }

    /**
     * @param btnPedidos the btnPedidos to set
     */
    public void setBtnPedidos(javax.swing.JMenuItem btnPedidos) {
        this.btnPedidos = btnPedidos;
    }

    /**
     * @return the btnProductos
     */
    public javax.swing.JMenuItem getBtnProductos() {
        return btnProductos;
    }

    /**
     * @param btnProductos the btnProductos to set
     */
    public void setBtnProductos(javax.swing.JMenuItem btnProductos) {
        this.btnProductos = btnProductos;
    }

    /**
     * @return the btnProveedores
     */
    public javax.swing.JMenuItem getBtnProveedores() {
        return btnProveedores;
    }

    /**
     * @param btnProveedores the btnProveedores to set
     */
    public void setBtnProveedores(javax.swing.JMenuItem btnProveedores) {
        this.btnProveedores = btnProveedores;
    }

    /**
     * @return the btnReportes
     */
    public javax.swing.JMenuItem getBtnReportes() {
        return btnReportes;
    }

    /**
     * @param btnReportes the btnReportes to set
     */
    public void setBtnReportes(javax.swing.JMenuItem btnReportes) {
        this.btnReportes = btnReportes;
    }

    /**
     * @return the btnReportesClientes
     */
    public javax.swing.JMenuItem getBtnReportesClientes() {
        return btnReportesClientes;
    }

    /**
     * @param btnReportesClientes the btnReportesClientes to set
     */
    public void setBtnReportesClientes(javax.swing.JMenuItem btnReportesClientes) {
        this.btnReportesClientes = btnReportesClientes;
    }

    /**
     * @return the btnReportesContables
     */
    public javax.swing.JMenuItem getBtnReportesContables() {
        return btnReportesContables;
    }

    /**
     * @param btnReportesContables the btnReportesContables to set
     */
    public void setBtnReportesContables(javax.swing.JMenuItem btnReportesContables) {
        this.btnReportesContables = btnReportesContables;
    }

    /**
     * @return the btnReportesMenu
     */
    public javax.swing.JMenu getBtnReportesMenu() {
        return btnReportesMenu;
    }

    /**
     * @param btnReportesMenu the btnReportesMenu to set
     */
    public void setBtnReportesMenu(javax.swing.JMenu btnReportesMenu) {
        this.btnReportesMenu = btnReportesMenu;
    }

    /**
     * @return the btnReportesProductos
     */
    public javax.swing.JMenuItem getBtnReportesProductos() {
        return btnReportesProductos;
    }

    /**
     * @param btnReportesProductos the btnReportesProductos to set
     */
    public void setBtnReportesProductos(javax.swing.JMenuItem btnReportesProductos) {
        this.btnReportesProductos = btnReportesProductos;
    }

    /**
     * @return the btnReportesProveedores
     */
    public javax.swing.JMenuItem getBtnReportesProveedores() {
        return btnReportesProveedores;
    }

    /**
     * @param btnReportesProveedores the btnReportesProveedores to set
     */
    public void setBtnReportesProveedores(javax.swing.JMenuItem btnReportesProveedores) {
        this.btnReportesProveedores = btnReportesProveedores;
    }

    /**
     * @return the btnResetearClave
     */
    public javax.swing.JMenuItem getBtnResetearClave() {
        return btnResetearClave;
    }

    /**
     * @param btnResetearClave the btnResetearClave to set
     */
    public void setBtnResetearClave(javax.swing.JMenuItem btnResetearClave) {
        this.btnResetearClave = btnResetearClave;
    }

    /**
     * @return the btnRetenciones
     */
    public javax.swing.JMenuItem getBtnRetenciones() {
        return btnRetenciones;
    }

    /**
     * @param btnRetenciones the btnRetenciones to set
     */
    public void setBtnRetenciones(javax.swing.JMenuItem btnRetenciones) {
        this.btnRetenciones = btnRetenciones;
    }

    /**
     * @return the btnSeguridad
     */
    public javax.swing.JMenu getBtnSeguridad() {
        return btnSeguridad;
    }

    /**
     * @param btnSeguridad the btnSeguridad to set
     */
    public void setBtnSeguridad(javax.swing.JMenu btnSeguridad) {
        this.btnSeguridad = btnSeguridad;
    }

    /**
     * @return the btnTipoDocumento
     */
    public javax.swing.JMenuItem getBtnTipoDocumento() {
        return btnTipoDocumento;
    }

    /**
     * @param btnTipoDocumento the btnTipoDocumento to set
     */
    public void setBtnTipoDocumento(javax.swing.JMenuItem btnTipoDocumento) {
        this.btnTipoDocumento = btnTipoDocumento;
    }

    /**
     * @return the btnUsuariosSistema
     */
    public javax.swing.JMenuItem getBtnUsuariosSistema() {
        return btnUsuariosSistema;
    }

    /**
     * @param btnUsuariosSistema the btnUsuariosSistema to set
     */
    public void setBtnUsuariosSistema(javax.swing.JMenuItem btnUsuariosSistema) {
        this.btnUsuariosSistema = btnUsuariosSistema;
    }

    /**
     * @return the btnVariablesParametrizables
     */
    public javax.swing.JMenuItem getBtnVariablesParametrizables() {
        return btnVariablesParametrizables;
    }

    /**
     * @param btnVariablesParametrizables the btnVariablesParametrizables to set
     */
    public void setBtnVariablesParametrizables(javax.swing.JMenuItem btnVariablesParametrizables) {
        this.btnVariablesParametrizables = btnVariablesParametrizables;
    }

    /**
     * @return the btnVentas
     */
    public javax.swing.JMenuItem getBtnVentas() {
        return btnVentas;
    }

    /**
     * @param btnVentas the btnVentas to set
     */
    public void setBtnVentas(javax.swing.JMenuItem btnVentas) {
        this.btnVentas = btnVentas;
    }

    /**
     * @return the btnVentasMensuales
     */
    public javax.swing.JMenuItem getBtnVentasMensuales() {
        return btnVentasMensuales;
    }

    /**
     * @param btnVentasMensuales the btnVentasMensuales to set
     */
    public void setBtnVentasMensuales(javax.swing.JMenuItem btnVentasMensuales) {
        this.btnVentasMensuales = btnVentasMensuales;
    }

    /**
     * @return the btnVentasdiarias
     */
    public javax.swing.JMenuItem getBtnVentasdiarias() {
        return btnVentasdiarias;
    }

    /**
     * @param btnVentasdiarias the btnVentasdiarias to set
     */
    public void setBtnVentasdiarias(javax.swing.JMenuItem btnVentasdiarias) {
        this.btnVentasdiarias = btnVentasdiarias;
    }

    /**
     * @return the jMenuBar1
     */
    public javax.swing.JMenuBar getjMenuBar1() {
        return jMenuBar1;
    }

    /**
     * @param jMenuBar1 the jMenuBar1 to set
     */
    public void setjMenuBar1(javax.swing.JMenuBar jMenuBar1) {
        this.jMenuBar1 = jMenuBar1;
    }

    /**
     * @return the btnResetarClaveAdmin
     */
    public javax.swing.JMenuItem getBtnResetarClaveAdmin() {
        return btnResetarClaveAdmin;
    }

    /**
     * @param btnResetarClaveAdmin the btnResetarClaveAdmin to set
     */
    public void setBtnResetarClaveAdmin(javax.swing.JMenuItem btnResetarClaveAdmin) {
        this.btnResetarClaveAdmin = btnResetarClaveAdmin;
    }
}
